import { defineConfig } from 'vite-plus'

export default defineConfig({
	staged: {
		'*': 'vp check --fix',
	},
	lint: {
		plugins: ['oxc', 'typescript', 'unicorn', 'react', 'import', 'node', 'jsdoc'],
		categories: {
			correctness: 'warn',
		},
		options: {
			typeAware: true,
			typeCheck: true,
		},
		env: {
			builtin: true,
			es2026: true,
			browser: true,
			node: true,
		},
		ignorePatterns: [
			'**/dist',
			'**/bun.lockb',
			'**/.idea',
			'**/*.min.*',
			'**/node_modules',
			'**/*.tsbuildinfo',
			'**/.env',
			'**/.DS_Store',
		],
		rules: {
			'constructor-super': 'error',
			'for-direction': 'error',
			'getter-return': 'error',
			'no-async-promise-executor': 'error',
			'no-case-declarations': 'error',
			'no-class-assign': 'error',
			'no-compare-neg-zero': 'error',
			'no-cond-assign': 'error',
			'no-const-assign': 'error',
			'no-constant-binary-expression': 'error',
			'no-constant-condition': 'error',
			'no-control-regex': 'error',
			'no-debugger': 'error',
			'no-delete-var': 'error',
			'no-dupe-class-members': 'error',
			'no-dupe-else-if': 'error',
			'no-dupe-keys': 'error',
			'no-duplicate-case': 'error',
			'no-empty': 'error',
			'no-empty-character-class': 'error',
			'no-empty-pattern': 'error',
			'no-empty-static-block': 'error',
			'no-ex-assign': 'error',
			'no-extra-boolean-cast': 'error',
			'no-fallthrough': 'error',
			'no-func-assign': 'error',
			'no-global-assign': 'error',
			'no-import-assign': 'error',
			'no-invalid-regexp': 'error',
			'no-irregular-whitespace': 'error',
			'no-loss-of-precision': 'error',
			'no-misleading-character-class': 'error',
			'no-new-native-nonconstructor': 'error',
			'no-nonoctal-decimal-escape': 'error',
			'no-obj-calls': 'error',
			'no-prototype-builtins': 'error',
			'no-redeclare': 'error',
			'no-regex-spaces': 'error',
			'no-self-assign': 'error',
			'no-setter-return': 'error',
			'no-shadow-restricted-names': 'error',
			'no-sparse-arrays': 'error',
			'no-this-before-super': 'error',
			'no-unassigned-vars': 'error',
			'no-undef': 'error',
			'no-unexpected-multiline': 'error',
			'no-unreachable': 'error',
			'no-unsafe-finally': 'error',
			'no-unsafe-negation': 'error',
			'no-unsafe-optional-chaining': 'error',
			'no-unused-labels': 'error',
			'no-unused-private-class-members': 'error',
			'no-unused-vars': 'error',
			'no-useless-backreference': 'error',
			'no-useless-catch': 'error',
			'no-useless-escape': 'error',
			'no-with': 'error',
			'preserve-caught-error': 'error',
			'require-yield': 'error',
			'use-isnan': 'error',
			'valid-typeof': 'error',
			'array-callback-return': 'error',
			'block-scoped-var': 'error',
			eqeqeq: ['error', 'smart'],
			'no-alert': 'warn',
			'no-console': [
				'warn',
				{
					allow: ['warn', 'error', 'info', 'clear'],
				},
			],
			'no-inner-declarations': 'error',
			'no-lonely-if': 'error',
			'no-multi-str': 'error',
			'no-unused-expressions': [
				'error',
				{
					allowShortCircuit: true,
					allowTaggedTemplates: true,
					allowTernary: true,
				},
			],
			'no-useless-call': 'error',
			'no-useless-computed-key': 'error',
			'no-useless-constructor': 'error',
			'no-useless-rename': 'error',
			'no-var': 'error',
			'no-void': 'error',
			'prefer-const': [
				'warn',
				{
					destructuring: 'all',
					ignoreReadBeforeAssign: true,
				},
			],
			'prefer-exponentiation-operator': 'error',
			'prefer-rest-params': 'error',
			'prefer-spread': 'error',
			'prefer-template': 'error',
			'require-await': 'error',
			'unicode-bom': ['error', 'never'],
			'vars-on-top': 'error',
			yoda: [
				'warn',
				'never',
				{
					exceptRange: true,
				},
			],
			'no-use-before-define': [
				'error',
				{
					classes: false,
					functions: false,
					variables: true,
				},
			],
			'import/first': 'error',
			'import/no-duplicates': 'error',
			'import/no-mutable-exports': 'error',
			'import/no-named-default': 'error',
			'import/no-self-import': 'error',
			'import/no-webpack-loader-syntax': 'error',
			'no-duplicate-imports': [
				'error',
				{
					allowSeparateTypeImports: true,
				},
			],
			'unicorn/catch-error-name': 'error',
			'unicorn/consistent-date-clone': 'error',
			'unicorn/consistent-empty-array-spread': 'error',
			'unicorn/consistent-existence-index-check': 'error',
			'unicorn/consistent-function-scoping': [
				'error',
				{
					checkArrowFunctions: false,
				},
			],
			'unicorn/custom-error-definition': 'error',
			'unicorn/error-message': 'error',
			'unicorn/escape-case': 'error',
			'unicorn/new-for-builtins': 'error',
			'unicorn/no-array-method-this-argument': 'error',
			'unicorn/no-array-reverse': 'error',
			'unicorn/no-await-in-promise-methods': 'error',
			'unicorn/no-console-spaces': 'error',
			'unicorn/no-hex-escape': 'error',
			'unicorn/no-instanceof-builtins': 'error',
			'unicorn/no-invalid-remove-event-listener': 'error',
			'unicorn/no-lonely-if': 'error',
			'unicorn/no-negation-in-equality-check': 'error',
			'unicorn/no-new-array': 'error',
			'unicorn/no-new-buffer': 'error',
			'unicorn/no-single-promise-in-promise-methods': 'error',
			'unicorn/no-static-only-class': 'error',
			'unicorn/no-unnecessary-array-flat-depth': 'error',
			'unicorn/no-unnecessary-array-splice-count': 'error',
			'unicorn/no-unnecessary-await': 'error',
			'unicorn/no-unnecessary-slice-end': 'error',
			'unicorn/no-useless-error-capture-stack-trace': 'error',
			'unicorn/no-zero-fractions': 'error',
			'unicorn/prefer-add-event-listener': 'error',
			'unicorn/prefer-array-find': 'error',
			'unicorn/prefer-array-flat-map': 'error',
			'unicorn/prefer-array-index-of': 'error',
			'unicorn/prefer-array-some': 'error',
			'unicorn/prefer-at': 'error',
			'unicorn/prefer-blob-reading-methods': 'error',
			'unicorn/prefer-class-fields': 'error',
			'unicorn/prefer-date-now': 'error',
			'unicorn/prefer-dom-node-append': 'error',
			'unicorn/prefer-dom-node-dataset': 'error',
			'unicorn/prefer-dom-node-remove': 'error',
			'unicorn/prefer-dom-node-text-content': 'error',
			'unicorn/prefer-includes': 'error',
			'unicorn/prefer-keyboard-event-key': 'error',
			'unicorn/prefer-math-min-max': 'error',
			'unicorn/prefer-math-trunc': 'error',
			'unicorn/prefer-modern-dom-apis': 'error',
			'unicorn/prefer-modern-math-apis': 'error',
			'unicorn/prefer-negative-index': 'error',
			'unicorn/prefer-node-protocol': 'warn',
			'unicorn/prefer-number-properties': 'error',
			'unicorn/prefer-optional-catch-binding': 'error',
			'unicorn/prefer-prototype-methods': 'error',
			'unicorn/prefer-query-selector': 'error',
			'unicorn/prefer-reflect-apply': 'error',
			'unicorn/prefer-regexp-test': 'error',
			'unicorn/prefer-string-raw': 'error',
			'unicorn/prefer-string-replace-all': 'error',
			'unicorn/prefer-string-slice': 'error',
			'unicorn/prefer-string-starts-ends-with': 'error',
			'unicorn/prefer-string-trim-start-end': 'error',
			'unicorn/prefer-type-error': 'error',
			'unicorn/throw-new-error': 'error',
			'node/handle-callback-err': ['error', '^(err|error)$'],
			'node/no-exports-assign': 'error',
			'node/no-new-require': 'error',
			'node/no-path-concat': 'error',
			'jsdoc/check-access': 'warn',
			'jsdoc/empty-tags': 'warn',
			'jsdoc/require-param-name': 'warn',
			'jsdoc/require-returns-description': 'warn',
			// 'de-morgan/no-negated-conjunction': 'error',
			// 'de-morgan/no-negated-disjunction': 'error',
			'typescript/dot-notation': 'warn',
		},
		overrides: [
			{
				files: ['**/*.test.*'],
				rules: {
					'no-floating-promises': 'off',
				},
			},
		],
	},
	fmt: {
		endOfLine: 'lf',
		useTabs: true,
		semi: false,
		singleQuote: true,
		trailingComma: 'es5',
		printWidth: 120,
		sortImports: {
			groups: [
				'type-builtin',
				'type-external',
				'type-internal',
				'type-subpath',
				['type-parent', 'type-sibling', 'type-index'],
				'builtin',
				'bun',
				'external',
				'internal',
				'subpath',
				['parent', 'sibling', 'index'],
				'side_effect',
				'style',
				'unknown',
			],
			newlinesBetween: false,
			customGroups: [
				{
					groupName: 'bun',
					elementNamePattern: ['bun', 'bun:test'],
				},
			],
		},
		sortPackageJson: {
			sortScripts: true,
		},
		ignorePatterns: [],
	},
	test: {
		// Only these tests explicitly use vitest.
		include: ['packages/utils/test/*.test.ts'],
	},
})
