name: Run tests for pull requests

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Run Node.js Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22, 24]
    steps:
      - name: 👀 Checkout Code
        uses: actions/checkout@v4

      - name: 🏗 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: 🛠 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📦 Install Dependencies
        run: bun install

      - name: 🧪 Run Lint
        run: bun run lint

      - name: 🔨 Run build
        run: bun run build

      - name: 🧪 Run Tests (in Bun)
        run: bun run test

      - name: 🧪 Run Tests (in Node)
        run: node --run test:node

      - name: 🧪 Run Tests (in via npm in Bun)
        run: npm run test

      - name: 🧪 Run Tests (in via npm in Node)
        run: npm run test:node

      - name: 🧪 Run Dist Tests (in via npm in Node)
        run: npm run test:dist:node

  test-node-20:
    name: Run Tests in Node.js v20
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout Code
        uses: actions/checkout@v4

      - name: 🏗 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 🛠 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📦 Install Dependencies (via npm)
        run: npm install

      - name: 📦 Run build
        run: npm run build

      - name: 🧪 Run Tests
        run: npm run test

      - name: 🧪 Run Dist Tests (in Node via npm)
        run: npm run test:dist:node
